config/routes.rb
Rails.application.routes.draw do
  root "story#index"
  
  resources :stories

end

app/models/story.rb
class Story < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/story_controller.rb
# Rewsly (It's basically a blog)

####App Description

# The City Times needs an app and has hired BEWD students to build it. They want to enter the 21st century and move their print newspaper online.

# You will build Rewsly during lesson 11 & 12.

#s####Time: 60 min

# Here are the features needed by next class.

# For now City times is only interested in linking to other news sources instead of writing their own news.

# * The front page welcomes visitors "Welcome to Rewsly" and list all titles in the stories table.
# * Visitors can view a story's upvotes, category and link to more details by clicking on the title from the front page.
# * Visitors can search for a specific story by title and category from the front page.
# * Visitors can add stories to the database if all fields are present.
#   * Prevent visitors from saving a record if it has errors.


# We've supplied you with [story seeds](story_seeds.rb).

# __Bonus__

# * Only display stories with 4 or more upvotes on the front page.
# * Only display stories created today on the front page.

# Remember, Google is your friend!

# Happy coding :)

class StoryController < ApplicationController

  before_action :load_story, only: [:edit, :show, :update]

  def index
    @stories = Story.all
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(safe_story_params)
    if @story.save
        redirect_to @story
    else
        render 'new'
    end
  end

  def edit
  end

  def update
  end

  def show
  end

  private
    def safe_story_params
      params.require('story').permit(:title, :link, :upvotes, :category)
    end
    
    def load_story
      @story = Story.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash.now[:notice] = "Invalid Story #{params[:id]}"
      redirect_to root_path
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/story_helper.rb
module StoryHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rewsly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/story/create.html.erb
<h1>Story#create</h1>
<p>Find me in app/views/story/create.html.erb</p>

app/views/story/edit.html.erb
<h1>Story#edit</h1>
<p>Find me in app/views/story/edit.html.erb</p>

app/views/story/index.html.erb
<h1>Welcome to Rewsly!</h1>

<h3><%= link_to "+ Add New Story", new_story_path %></h3>

<%= form_tag stories_path, method: "GET" do %>
	<%= text_field_tag :q, params[:q] %>
	<%= submit_tag "Search Stories" %>
<% end %>

<br/>

<% @stories.each do |story| %>
	<section>
		<h3><%= link_to story.title, story %></h3>
		<p>
			===========================================
		</p>
	</section>
<% end %>

app/views/story/new.html.erb
<h1>Story#new</h1>
<p>Find me in app/views/story/new.html.erb</p>

app/views/story/show.html.erb
<!-- if coming from search page
	only show those stories

else -->
	<h1><%= @story.title %></h1>
	<h2><%= "Category:" @story.category %></h2>
	<h3><%= "Upvotes:" @story.Upvotes %></h3>
	<p><%= "More details:" @story.link %></p>
<!-- end -->

app/views/story/update.html.erb
<h1>Story#update</h1>
<p>Find me in app/views/story/update.html.erb</p>